# Generated by Django 6.0.1 on 2026-02-01 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliate_url', models.URLField()),
                ('network', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Affiliate Product',
                'verbose_name_plural': 'Affiliate Products',
            },
        ),
        migrations.CreateModel(
            name='BlacklistTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blacklist Term',
                'verbose_name_plural': 'Blacklist Terms',
                'ordering': ['-severity', 'term'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('effectiveness_avg', models.FloatField(default=0.0)),
                ('difficulty_avg', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='wiki.category')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('ai', 'AI Detection'), ('manual', 'Manual Review')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('matched_terms', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('ip_hash', models.CharField(max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flags', to='wiki.tip')),
            ],
            options={
                'verbose_name': 'Moderation Flag',
                'verbose_name_plural': 'Moderation Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('ip_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='wiki.tip')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('flag_created', 'Flag Created'), ('flag_approved', 'Flag Approved'), ('flag_rejected', 'Flag Rejected'), ('tip_rejected', 'Tip Rejected'), ('user_warned', 'User Warned'), ('user_suspended', 'User Suspended')], max_length=50)),
                ('ip_hash', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wiki.moderationflag')),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='wiki.tip')),
            ],
            options={
                'verbose_name': 'Moderation Log',
                'verbose_name_plural': 'Moderation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='wiki_modera_action_cc8e04_idx'), models.Index(fields=['created_at'], name='wiki_modera_created_769046_idx'), models.Index(fields=['ip_hash'], name='wiki_modera_ip_hash_ec09ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='moderationflag',
            index=models.Index(fields=['status'], name='wiki_modera_status_08f431_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationflag',
            index=models.Index(fields=['flag_type'], name='wiki_modera_flag_ty_4adeb0_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationflag',
            index=models.Index(fields=['created_at'], name='wiki_modera_created_cec18a_idx'),
        ),
    ]
