# Generated by Django 6.0.1 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
