# Generated by Django 6.0.1 on 2026-02-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_add_tip_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
