# Generated by Django 6.0.1 on 2026-02-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
